//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attributes
    {
        public int AttributeID { get; set; }
        public int ArtefactID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Value { get; set; }
    
        public virtual Artefacts Artefacts { get; set; }
    }
}
